### PR TITLE
More Backports + Fix

### PR DESCRIPTION
**Pull request by drammelt**
Backports in notification module.
Also a fix I found where windows that were maximized bugged out if sent to other monitors.

### CODE REVIEW

**Comment by JeffHoogland** [comment]
Thanks for continuing to go through these. I'll be checking to make sure they all compile AOK and starting to do some of my own additions in the next week or two.

**Comment by drammelt** [comment]
I am running on Gentoo so there maybe some differences, although I have not touched the Makefiles.
I am using the Head of my repo as my work desktop and it is amazing stable/bug free compared to E17.6 which I always found quite buggy for my given workflow.
It is also markedly better than E19 which seems to have a huge number of regressions still.

**Comment by JeffHoogland** [comment]
That is awesome to know. Does your repo have any changes that aren't in this one here? 

A lot of what I am going to be doing is just adding a few extras. I want to merge the places and epulse modules into the core and make a more sane default profile to go with the more trim startup wizard.

We (well Duma) will also be crafting a more neutral default theme at some point.

**Comment by drammelt** [comment]
No I am running right now with exactly what is in the head of your repo. The notification patches I put through in the previous pull request were my last blocker for full use. Since I use wyrd with notify-send as my calendar/reminder system.
If i hadnt seen the blog about Moksha I would never have started doing these backports, never even thought to look into it. Pleased I did, as it works so well. Every other DE I used had some compromise (Fluxbox/KDE/E19/E17) where a bug would mean I had to do things a certain way to get the results I wanted.
The biggest of these was the seperate workspaces per desktop as in E. All great now :)

**Pull request merged**
