### PR TITLE
pt.po update

### PR DESCRIPTION
**Pull request by hugok79**
Portuguese translation update

### CODE REVIEW

**Comment by thewaiter** [comment]
Hi Hugo, can you look at new translations pls?

msgid "Operation failed"
msgid "Unknown error"
msgid "This Desktop Settings"

THX

**Comment by hugok79** [comment]
> Hi Hugo, can you look at new translations pls?
> 
> msgid "Operation failed" msgid "Unknown error" msgid "This Desktop Settings"�
> 
> THX

Yes, I Will take a look later today.

**Comment by hugok79** [comment]
@thewaiter Done! https://github.com/JeffHoogland/moksha/pull/190

**Comment by thewaiter** [comment]
thx mate :)

**Pull request merged**
