### PR TITLE
Backport: Several changes to fix one issue with eeze_scanner

### PR DESCRIPTION
**Pull request by drammelt**
Merged several commits from master git. This fixes an issue with eeze_scanner (e_fm) causing excessive CPU usage/defunct e_fm processes.

### CODE REVIEW

**Comment by drammelt** [comment]
Finished skimming core (src/bin) master git for fixes to current code. I have not looked at the modules other than where they were referenced by core E fixes.

**Comment by JeffHoogland** [comment]
Thanks again for taking the time to work on all of these. I'll be sitting down to really start doing work on this code base for the few changes / merges I want to make in early June (maybe before then if I can manage)

**Comment by drammelt** [comment]
No worries, the only outstanding issue I have now is initial window placement sometime being put under shelves when the shelf is at the top of the screen. This is broken in master git also. I will continue to back port any newer commits from master, and may look at the modules at some point if I get time.

**Comment by JeffHoogland** [comment]
That is a really frustrating issue that E has always had. I really wish it would NEVER open a window at least to start partially off the screen. Will be one of the things I will be looking into implementing as it leads to user frustration (my own included!)

**Pull request merged**
